client:
    pattern:  /
    defaults: { _controller: "MyAppProjetFinalBundle:client:index" }

client_show:
    pattern:  /{id}/show
    defaults: { _controller: "MyAppProjetFinalBundle:client:show" }

client_new:
    pattern:  /new
    defaults: { _controller: "MyAppProjetFinalBundle:client:new" }

client_create:
    pattern:  /create
    defaults: { _controller: "MyAppProjetFinalBundle:client:create" }
    requirements: { _method: post }

client_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MyAppProjetFinalBundle:client:edit" }

client_update:
    pattern:  /{id}/update
    defaults: { _controller: "MyAppProjetFinalBundle:client:update" }
    requirements: { _method: post|put }

client_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MyAppProjetFinalBundle:client:delete" }
    requirements: { _method: post|delete }
