parameters:
#    my_app_projet_final.example.class: MyApp\ProjetFinalBundle\Example

services:
#    my_app_projet_final.example:
#        class: %my_app_projet_final.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
