MyApp\ProjetFinalBundle\Entity\services:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        type:
            type: string
            length: 255
        description:
            type: string
            length: 255
        gouvernorat:
            type: string
            length: 255
        delegation:
            type: string
            length: 255
        prix:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
